### ISSUE TITLE
Partition Size

### ISSUE THREAD

**Issue by amanharitsh123** [amanharitsh123/sugarizer-school-box#11]
By default , bmaptool make a 4Gb partition on my sdcard . Leaving all other space as free. 
Have to resize partition manually after flashing.

**Comment by quozl** [comment]
https://github.com/drtyhlpr/rpi23-gen-image/blob/master/files/firstboot/22-expandroot.sh does this step, but the file is no longer in your repository.

It was moved in https://github.com/amanharitsh123/sugarizer-school-box/commit/735f49df66d3618743c1d383bdd1bb23964d6114.

It was removed in https://github.com/amanharitsh123/sugarizer-school-box/commit/c1966507eb0fde8ff6026d66332827c01bbd4f8f.

If you are still using it, you might add logging to find out why it isn't running.

**Comment by amanharitsh123** [comment]
@quozl  Thanks , I have found the bug :)

**Comment by amanharitsh123** [comment]
Fixed in a5a9861
