### ISSUE TITLE
Make a release version

### ISSUE THREAD

**Issue by quozl** [amanharitsh123/sugarizer-school-box#17]
Suggested steps for making a release;

* [x] wait to be finished most of what you planned,
* [x] choose a version number,
* [x] use `git tag v1.0` and `git push --tags`,
* [x] verify you see it in [Releases](https://github.com/amanharitsh123/sugarizer-school-box/releases),
* [x] also push to the [Sugar Labs](https://github.com/sugarlabs/sugarizer-school-box) repository,
* [x] verify you see it in [Releases](https://github.com/sugarlabs/sugarizer-school-box/releases) there,
* [x] upload a zip or tar.gz to your sunjammer account, (as a backup in case GitHub is down),
* [x] announce the release on sugar-devel@,

You've been [invited](https://github.com/sugarlabs/sugarizer-school-box/invitations) to be a collaborator on the Sugar Labs repository.

**Comment by amanharitsh123** [comment]
@quozl  Thank you for highlighting these steps. I am starting working on them and will release a image soon.

**Comment by amanharitsh123** [comment]
@quozl Please review.

**Comment by quozl** [comment]
Thanks.
