### ISSUE TITLE
FirstBoot Actions Not Working 

### ISSUE THREAD

**Issue by amanharitsh123** [amanharitsh123/sugarizer-school-box#5]
script.sh in custom_scripts doesnt work at the firstboot.

**Comment by quozl** [comment]
In file sugarizer.sh you prefix almost everythinkg with ${R} (the root filesystem), but not your write to rc.firstboot; you may find you have added a line to your host system instead.

https://github.com/amanharitsh123/sugarizer-school-box/blob/dev/custom_scripts/sugarizer.sh#L5

**Comment by amanharitsh123** [comment]
${R} represents the root partition of the chroot system and {ETC_DIR} is /etc/ 
https://github.com/drtyhlpr/rpi23-gen-image/blob/master/rpi23-gen-image.sh#L92
I have confirmed that https://github.com/amanharitsh123/sugarizer-school-box/blob/dev/custom_scripts/sugarizer.sh#L5 places a line in /etc/rc.firstboot in the rpi image. But I dont know why the script.sh is not working.

**Comment by amanharitsh123** [comment]
@quozl  Please Review .
